from myLinkedList import myLinkedList
def testMyLinkedList():
	print("Creation")
	l = myLinkedList(5)
	print(l.toString())
	print("add end 4")
	l.addEnd(4)
	print(l.toString())
	print("add end 5")
	l.addEnd(5)
	print(l.toString())
	print("add end 6")
	l.addEnd(6)
	print(l.toString())
	print("delete 5")
	l = l.delete(5)
	print(l.toString())
	print("delete 5")
	l = l.delete(5)
	print(l.toString())
	print("add end 3")
	l.addEnd(3)
	print(l.toString())
	print("add end 2")
	l.addEnd(2)
	print(l.toString())
	print("add end 1")
	l.addEnd(1)
	print(l.toString())
	print("delete 6")
	l = l.delete(6)
	print(l.toString())
	print("delete 1")
	l = l.delete(1)
	print(l.toString())


if __name__ == '__main__':
	testMyLinkedList()
